/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TugasRouteImport } from './routes/tugas'
import { Route as MasterRouteImport } from './routes/master'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as IndexRouteImport } from './routes/index'

const TugasRoute = TugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/tugas': typeof TugasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/tugas': typeof TugasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/tugas': typeof TugasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/laporan' | '/login' | '/master' | '/tugas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/laporan' | '/login' | '/master' | '/tugas'
  id: '__root__' | '/' | '/laporan' | '/login' | '/master' | '/tugas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaporanRoute: typeof LaporanRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRoute
  TugasRoute: typeof TugasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tugas': {
      id: '/tugas'
      path: '/tugas'
      fullPath: '/tugas'
      preLoaderRoute: typeof TugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaporanRoute: LaporanRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRoute,
  TugasRoute: TugasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
